# DockerFile for go-docker-judger
FROM ubuntu:18.04
MAINTAINER pushyzheng

ENV HOME          /root
ENV JAVA_HOME     /usr/lib/jvm/java-8-openjdk-amd64

WORKDIR /root

# configure DNS server
RUN echo "nameserver 8.8.8.8" > /etc/resolv.conf

# configure aliyun mirror
COPY sources.list /root
RUN rm /etc/apt/sources.list
RUN cp /root/sources.list /etc/apt

RUN apt-get update

# Install Java
RUN apt-get install -y openjdk-8-jdk

# Install C/C++
RUN apt-get install -y git gcc g++ make

# Install Python
RUN apt-get install -y python3
RUN ln -s /usr/bin/python3 /usr/bin/python

# Install nodejs
RUN apt-get install -y nodejs

# Install tools
RUN apt-get install -y time
